name: mariposa
description: Virtual DOM framework powered by Incremental DOM. Heavily reminiscent of Flutter.
version: 1.1.0-alpha.2
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/mariposa-dart/mariposa
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_container: ^1.0.0-alpha
  html_builder: ^1.0.0
  js: ^0.6.1
  meta: ^1.0.0
  zen: ^1.0.0
dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  mariposa_test: ^1.0.0