name: mariposa
description: Virtual DOM library.
version: 1.0.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/mariposa-dart/mariposa
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  html_builder: ^1.0.0
  js: ^0.6.1
  zen: ^1.0.0
dev_dependencies:
  build_runner: ^0.8.0
  build_web_compilers: ^0.4.0