name: angel_mariposa
description: Angel framework bindings for Mariposa, enabling server-side rendering for SPA's and more.
version: 1.0.0-dev
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/mariposa-dart/mariposa
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0
  mariposa: ^2.0.0-alpha
  universal_html: ^1.0.0
dev_dependencies:
  logging: ^0.11.0
  pedantic: ^1.0.0
  pretty_logging: ^1.0.0
  test: ^1.0.0
dependency_overrides:
  mariposa:
    path: ../mariposa
