name: tap
description: Port of the Flutter example
dependencies:
  js: ^0.6.1
  mariposa:
    path:
      ../../
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.0
transformers:
- dart_to_js_script_rewriter