name: mariposa
description: Virtual DOM framework powered by Incremental DOM. Heavily reminiscent of Flutter.
version: 2.0.0-dev
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/mariposa-dart/mariposa
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  html_builder: ^1.0.0
  immutable_state: ^1.0.0
  js: ^0.6.0
  merge_map: ^1.0.0
  meta: ^1.0.0
  universal_html: ^1.0.0
dev_dependencies:
  angel_framework: ^2.0.0
  build_runner: ^1.0.0
  build_web_compilers: ^2.0.0
  logging: ^0.11.0
  pedantic: ^1.0.0
  pretty_logging: ^1.0.0
  recase: ^2.0.0
  test: ^1.0.0
