name: hydrate_app
dependencies:
  angel_mariposa:
    path: ../../
  angel_proxy: ^2.0.0
  angel_static: ^2.0.0
  mariposa:
    path: ../../../mariposa
dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^2.0.0
  logging: ^0.11.0
  pedantic: ^1.0.0
  pretty_logging: ^1.0.0
  test: ^1.0.0
dependency_overrides:
  mariposa:
    path: ../../../mariposa