name: todo
publish_to: none
dependencies:
  angel_framework: ^1.0.0
  angel_static: ^1.0.0
  mariposa:
    path: ../../
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.0
transformers:
- dart_to_js_script_rewriter